Add New Features: Global Init Scripts, Secret Scope Creation, auto-run one-time setup with python file
SHARANTANGEDA/databricks-workspace-migrator pull request #1
Opened 2021-05-27 17:51 UTC by SHARANTANGEDA

Add Global Init Scripts Import, Secret Scope creation, auto python job run

Auto Python Job - Creates cluster, runs a specified python file, delete job configuration (Ud use-case: for tables-mounting)

Secret Scope Creation - Automatically mount secret scope

2021-05-27 17:54 UTC, SHARANTANGEDA commented
@manuhg, @mohit-udaan Have added few features on top of databrick's migrator these will help us completely automate the process.

2021-06-01 06:00 UTC, manuhg requested changes

2021-06-01 06:00 UTC, manuhg commented on data/dp_mount_points.py
> +
for loops need to go and become parallel maps

2021-06-01 06:01 UTC, manuhg commented on data/feast_global_init.sh
> +/databricks/python/bin/pip install confluent_kafka
all this can be just 1 stmt

2021-06-22 06:11 UTC, manuhg requested changes
hey left some suggestions. please look into

2021-06-22 06:11 UTC, manuhg commented on data/azure_cluster.json
> -    "cluster_name": "API_Metastore_Work_Leave_Me_Alone",
:joy:

2021-06-22 06:11 UTC, manuhg commented on data/dp_mount_library.py
> +                 'spClientSecret', 'spClientId', 'spTenantId', "dp-clientaccess")
try not to hardcode these things. also i thought you are using a different storage for storing feast utils and migration related things

2021-06-22 06:11 UTC, manuhg commented on data/dp_mount_library_v2.py
> +                         scope="dp-clientaccess", key="ds-common-storage-key")
how about adding this in mount points table and running setup mountpoints with a different the appropriate mount points category?

2021-06-22 06:11 UTC, manuhg commented on data/dp_mount_points.py
> +ddl_all()
in case you just want to import any function from this file, every time you import the ddl_all will run.

this is a bad way of doing things. please wrap these atleast in a main function or something of that sort

2021-06-22 06:11 UTC, manuhg commented on data/dp_mount_user_tables.py
> +ddl_all(df)
same name? would it not be confusing?

2021-06-22 06:11 UTC, manuhg commented on dbclient/JobsClient.py
> +        else:
do we support single node as well?

2021-08-18 14:44 UTC, closed without merging

2021-08-18 14:44 UTC, SHARANTANGEDA commented
deleting this